### ISSUE TITLE
FB user feedback - rethink

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#101]
Some feedback from a church member:
"Did a quick test and not super happy with how all the facebook posts look... I'd prefer it only shows the last one or two, and not all the images randomly like that (doesn't make sense to visitors).
Can you please turn off that functionality from our simple church page?  I've removed the app permissions from within Facebook."

Valid points, 
My cents: Looking at the feeds coming in, you end up with 8 old 'coming this week' text posts, and 1 relevant. Maybe if we drop back to 3, it would solve the overlapping issues which is not acceptable now either.
As for the FB photo section, I think they are spot on too - it is rather pointless in practically all instances I've seen. 
it could be managed better once they have access - but it's no longer simple church but a CMS if you need to manicure every post and pic.
Guess they can turn the features off if they don't want it. We're all good then :?
haha

**Comment by danlewis** [comment]
I think we should reevaluate each feature and see how its been used.

Photos from Facebook is probably a good candidate for the chopping block.
