### ISSUE TITLE
Can't add listing photo

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#102]
says uploading 100% when addiing an image to a listing. but then get's stuck saying 'adding to server' (see attached.)
![screen shot 2017-08-23 at 2 38 43 pm](https://user-images.githubusercontent.com/13688091/29599106-e61aaf46-8810-11e7-92e6-d61642b48161.png)

**Comment by Scotttie** [comment]
NOTE TO SCOTT: need to add cabramatta church image when working

**Comment by danlewis** [comment]
not an issue in version 2
