### ISSUE TITLE
SC File Storage Options

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#107]
File storage is required for bulletins mainly - and not being able to do this has deterred a few, but could be newsletters, powerpoints, forms too. (maybe podcast files???) Not really sure ho much this is needed as you have photo's covered already.

Would the process be, if they really wanted file storage, that they create an account in one of the below, and manage it themselves, then SC just allows you to:
- view the files to link to from SC
- upload files into from within SC
- display the file/s in a 'folder' as a list view in a SC card (eg show bulletins). 

My API knowledge is limited, but here's 3 popular options and api info links - not very helpful sorry.
Connecting one or more of these services I reckon:

Google drive
15gb free for users.
https://developers.google.com/drive/v3/web/about-sdk

iCloud drive
5gb free for users
https://developer.apple.com/icloud/icloud-drive/

Dropbox
2gb free
https://www.dropbox.com/developers

**Comment by danlewis** [comment]
sorted
