### ISSUE TITLE
Facebook Event showing (and ugly) on News section.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#11]
An added event shows correctly in the events section but there is a FB post about the event too (it created by default once an event is created) which appears on the SC News section.
So, in the news feed of SC we end up with duplicate content (event in news and events) but the News version image is cropped badly. (it does link to the event correctly however).
I think it should not appear in the news section, if possible, else if there is no option but to have it show, it should show more details or better image.
![screen shot 2017-02-21 at 10 03 57 am](https://cloud.githubusercontent.com/assets/13688091/23144669/4ffb4e18-f81d-11e6-86e6-31f2eaee9b5b.png)

**Comment by brettdonald** [comment]
I think it should show in the news section at the time it is created. Facebook puts it in the news feed, so should SC. That's where most people would find it.

**Comment by Scotttie** [comment]
No longer duplicates. They news and events appear next to each other, and news feed only has 3 slots so have kept it separate to allow for more variety of content on the page. number of news items and duplication could be re-looked at when the churches are going harder on their FB to see some trends we need to display better.
