### ISSUE TITLE
Decline message

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#110]
1. After I submitted an access request I got a green bar conformation at bottom of screen "successfully added Hello World to ..." - it should be 'request sent'
2. The notifications dropdown bell icon needs a 'view' link on requests
3. The top level dashboard - it needs to list requests where the "Admin: Site Requests to Approve" is shown
4. I typed a message in my application, but didn't see it anywhere as an admin. Should it appear in the email, and also somewhere on the site?
5. if you decline, can you state why or send a message to the user.

**Comment by danlewis** [comment]
1. message fixed
2. done
3. moved to admin. now shows all pending requests from all sites
4. Approval moved to membership page. Message showing with accept/decline options.
5. not at present

**Comment by Scotttie** [comment]
Keeping this ticket open for this future feature request:
- if you decline, can you state why or send a message to the user.

**Comment by danlewis** [comment]
decline feature added

**Comment by danlewis** [comment]
FYI: declined memberships are automatically deleted every hour

**Comment by Scotttie** [comment]
1. I like not being able to re-request access immediately, is there a way to request again should the situation change though? perhaps manually from inside?

2. the decline message window is good thanks. I can't remember the actual info box, can you make sure it says "Send reason for decline" or the like, just to make sure the admin knows what they write will go to the declined and they don't put in "this guy's a pest" thinking it's an internal note only

**Comment by Scotttie** [comment]
3. my declined membership in Hello World is still there after an hour, and i have no way to become a member with this MyAd account now, it seems.
https://dashboard.adventist.place/dashboard/sites/1/memberships

**Comment by danlewis** [comment]
1. we discussed this and i can't remember the conclusion but i think it's sorted :)
2. a hint appears under reason now: "Reason will be sent to user as a notification"
3. Should now be deleting (i hadn't deployed that update yet it turns out)
