### ISSUE TITLE
Dashboard-ish bits

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#111]
- As a site member, on dashboard I go to 'view all' [sites] then click on the menu dots RHS and click 'edit' of a site I am a member of but get 'not authorised'. It works if i am an admin, or works as a member if i click on the row.

- The top LHS menu icon, when on Dashboard topest level - is not needed.

- Search bar disappears for mobile view

**Comment by danlewis** [comment]
Authorised issue should be fixed

Nav added for dashboard.

Yes search disappears - this is intended for the time been on mobile.
