### ISSUE TITLE
Request Reminder featuer

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#113]
If there's already a site owner - after someone else submitting a request for access, what if the first site owner does not get back to them?
Can the new member resubmit to 'poke' the current admin? What do they do if they never hear back? What if they ARE the real deal and the previous owner is dead at their computer, or now atheist, or Buddhist and reincarnated as a fly who isn't heavy enough to press the mouse button to click approve....
I see 'pending site requests' area - maybe that can have a date and a resubmit button appears after X days - and a resubmit goes to a conference too???

**Comment by danlewis** [comment]
Weekly email reports are now sent each monday to admins and supporter admins.

These notify of new sites added and pending site access requests
