### ISSUE TITLE
Sugest Cloud changes form 500 error

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#115]
-update info link, as member, says 'not authorized' - should open a form to be able to enter content to update -that goes to conference?

- update info link, as admin says 'successfully updated' but nothing is updated, cant do so. 

- the representative blue dot initials are too small.

- view more or less cloud on site dashboard?? Do we want/need more info displayed from Adventist cloud? eg the set Conference, timezone, map? Having said this, this will load every time a user comes in, but it isn't even editable. Maybe the full info can be expandable, not loading by default as is now?

**Comment by danlewis** [comment]
It always did feel a little out of place there. I've moved it all under settings.

Authorisation issue should be resolved.

Update info link is working as expected. - It pulls in any changes from Adventist Cloud and updates them. There aren't any changes, hence nothing changes.

The representatives images are currently placeholder ones I added, so thats all good.

I've added more details that pulled from Adventist Cloud

**Comment by Scotttie** [comment]
Can the Manage area on the About Place page , below Fetch Changes, include a 'Suggest changes' that goes to the cloud  for review and approval. (the process when a webmaster goes, "hey that's wrong, it should be this - how to i get it changed..."

**Comment by danlewis** [comment]
As Adventist Cloud doesn't currently exist, if I've added a suggest a change action which opens an email with the subject prefilled.

In the future we change this out for a proper form.

**Comment by Scotttie** [comment]
Will keep opened as a reminder

**Comment by danlewis** [comment]
Adventist Cloud exists. Suggestion feature implemented :)

**Comment by Scotttie** [comment]
500 error presently, on submit.
