### ISSUE TITLE
Authorized Issues

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#116]
- Whenever I get a 'you are not authorised to view this page' while in a site's dashboard, I am kicked back to the SC main Dashboard and given the red bar of shame on the bottom. If unauthorised items can not be removed from view/clickability, can we stay on the same page and only show the red bar of shame?

- 'authorized' (on red bar of shame) should be spelt 'authorised' for SPD spelling, not US.

**Comment by danlewis** [comment]
resolved. please verify
