### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#117]
- events time selection is unhelpfully blank (no format displayed or chooser), however once trying to save it adds todays date automatically.

- when there WAS an event time thingy - there's clock icon and a calendar icon that interchanges when clicking, however no calendar shows up, it stays as the clock.

It appears you can set a finish time earlier than the start time - that's going to cause an issue for those who can not walk backwards while holding a try of hot soup.

There is no character limit on the event summary - that may be ok, depending on how you're going to display it. Good to have a lot of space to explain.

event search is only name of event, could searching summary text as secondary listed results be useful also? Searching for a pizza night, but the event was actually titled 'Italian round food night.' Maybe useful but probably not THAT useful - only if easy.

- event dropdown arrows are ugly in IOS FF

- can you manually add a default calendar for me, in Hello world. Pretty please? Or reinstall the entire site?

**Comment by danlewis** [comment]
All issues resolved in latest release. Please check
