### ISSUE TITLE
Social

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#118]
- Is there is a social account listed, the RHS 'three dot menu' could include a link to the actual social account.

- Add FB account gave a 500 when saving

- ability, for FB, to turn off/on events, posts, footer link, (photos/albums) etc, is any of that needed now?

- add account and icons is disconnected. I clicked on the icons hoping to go to that account page, not noticing the 'add account'.
Can they be bound together with an encompassing boarder or something, not sure. Even just a : at the end of text, and made a bit closer??

- social accounts - could they be housed/edited on Adventist Cloud too??

**Comment by danlewis** [comment]
Link to social account now on show page.

FB error should now be fixed.

Improved show page for social accounts with ability to subscribe to posts and more.

**Comment by Scotttie** [comment]
When I add a Facbook page, the view social account link puts a space in the name.
eg my account is sabbathideas and the link goes to sabbath%20ideas (which breaks)
https://dashboard.adventist.place/dashboard/sites/1/facebook_accounts/4
think it's taking the page title not 'page url' to make the link.

**Comment by danlewis** [comment]
Fixed url
