### ISSUE TITLE
Domains for Dummies

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#119]
Reminder to add some info of DNS settings needed
Probably near the 'Add domain' button, something like "Point the CNAME of your domain to [CNAME set in master admin]." for a start.
Maybe even mention you need to own a custom domain before you can set it up etc etc (i see a lot of custom domains in netA of people trying to get a name working without buying one.
- domains confuse 'simple' people big time. This needs to be written well once we know all the details.

**Comment by danlewis** [comment]
I have a fair idea of how it will now work - maybe if you could work with me on writing instructions

**Comment by Scotttie** [comment]
What you have now is probably sufficient for now - we'll see if we get any confusion.
