### ISSUE TITLE
Facebook Page name link destination? (news)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#12]
In the news section, the clickable name of the FB Page goes to /# of the SC address.
eg http://farleigh.adventistchurch.com/#

I think it shoudl go to their  FB Page.
![screen shot 2017-02-21 at 9 55 48 am](https://cloud.githubusercontent.com/assets/13688091/23144791/377fdf24-f81e-11e6-922d-a59fd877a3d8.png)

**Comment by danlewis** [comment]
Please check

**Comment by Scotttie** [comment]
Title appears again (was missing) but goes to the post. In FB that link goes to the Timeline home, not that post. Clicking an image currently goes to that post, probably ok in that instance to see the full image?
Look at https://demo.adventistchurch.com/ and decide where you expect the link to go when clicked.
