### ISSUE TITLE
Page Editor icons not displaying

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#121]
- 'preview page' eye icon is 500 error on click

- adding banner, podcast, news, events, contact cards - there is no 'move order' arrows or edit icons

-in fact, adding they show on same row. (related to above issue perhaps)

- there's no 'box' around the list of cards on the page, except the two column card and maps does have a white box. can they all have a visual box?

- top and bottom cards don't need an up AND down arrow

- on the column 1 or 2 content - when I add an image, it doesn't stay. Text and embed works
ALSO add image card, does not actually add selected imageeither

- Video embed card needs instruction of what code it needs

- can a header (for a banner) and footer (for contact) card set be set in the theme/layout/template???? to be applied site wide. an idea

- text editor toolbar icons are not displaying

- hard to see the edit icons on the embedded video or image cards - until rolled over. permanent backgrounds could be set on them?

- SLUG: instead of trying to explaining this to the web illiterate going to be using this, how about displaying it like this:
![slug](https://user-images.githubusercontent.com/13688091/31422370-dfa5fd2e-ae98-11e7-8f22-2b41e09e67b5.png)

- add a 'preview changes' view for before you hit save and do live to check your edits?

**Comment by danlewis** [comment]
1. preview page should be fixed when first theme is complete. please add as a separate issue.
2. actions should be be visible
3. i had tried adding a box although it had some weird visual results
4. arrows of first and last card hidden now
5. can you check if this is still happening
6. video embed description added
7. for now I don't think a banner is required on all pages (maybe we'll relook at this if we introduce page templates). 
8.
9. slug view updated
10. Preview changes isn't really possible as the the cards are saved when added/edited/deleted.

**Comment by Scotttie** [comment]
text editor toolbar icons are not displaying

**Comment by danlewis** [comment]
icons now display :)
