### ISSUE TITLE
mailing list

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#122]
mailchimp url - it's confusing asking for a URL when I don't know anything about where or what - I'm not gong to click 'add' until i think i know what I need to paste. Unfortunately the good instructions of where to get the info are hidden until you click add. Can the first 'add mailchimp' screen have all the info and no need to click 'add' to see the instructions. can the save button also do the 'get url' function and validate in one click?

Will just having a mail chimp name and url allow the user to add an 'entire' form will all fields? Or do we need to allow a html embed drop in area (we've discussed this before I'm sure).
what if there's a form with name, email, comments/I'm a youth/I'm a member type fields?
If not accommodating extra fields, it may be polite to note for the user, "Will display a sign up for with first name and email - no other form fields

**Comment by danlewis** [comment]
All features have been implemented

**Comment by Scotttie** [comment]
good work
