### ISSUE TITLE
contact submissions

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#123]
The ability to:
- add email address (like a church address) to receive the submissions that isn't a member of the site
- remove members from receiving messages
- add fields to the contact form (option)

**Comment by danlewis** [comment]
For the time been I'd prefer to have it all go through to the site admins.
This automatically helps maintain a current recipients list.

Also contact submissions are marked as unread when created and need to be set as read which can only be done by team member/admin. This helps ensure submissions are followed up. If the submission was only emailed to an address, you wouldn't know if it was really followed up.. although that could be done via a link in the email perhaps... get a bit tricker there.
