### ISSUE TITLE
view site (and general bitz...)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#124]
-  add link to 'view site' under the TopLHS site title so you can get there form any page in the site dashboard

- change the world icon to an eyecon (eye icon) on the 'list of pages' view

- Is dashboard search bar needed ALLLL the time, - eg when in editing a site?

- I assume there's a notification function in a SC HQ that can either go out to all or selected area site members?

- Clicking on 'terms of use' only gives me the option to sign in (i am already signed in) and can't go back.

- Note: terms of use is needed to be put in.

**Comment by danlewis** [comment]
1. View link site added at bottom on LHS menu
2. icon updated
3. yes
4. not yet. please open as seperate issue
5. clicking the product name on top left will navigate to correct place. It now only says sign in if not signed in.
6. please open as seperate issue
