### ISSUE TITLE
Admins adding new user: more info

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#130]
As Admin, i add go to add a new user manually, the drop down only gives the name.
there will be duplicate names (even of the same user with multiple account's like me (work and personal) and you can't tell who's who. If it showed their email also, that might help.

**Comment by danlewis** [comment]
i agree the duplicates would be an issue. however displaying email may not be the best option for privacy reasons.. otherwise someone could start finding the personal email addresses of any user.

Hopefully over time more people will add an icon and this will help with the issues

**Comment by Scotttie** [comment]
Good point re emails and privacy. 

The other side is you can add incorrect people to your site
eg, Danny Dell V Daniel Bell. 

will keep open as low priority enhancement for now.

**Comment by danlewis** [comment]
Closing as there's nothing to implement. If we do think of something we can reopen
