### ISSUE TITLE
Livestream Save - load list view

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#137]
was trying to save this in livestream then got a 500
https://www.youtube.com/watch?v=RtU_mdL2vBM

https://dashboard.adventist.place/dashboard/sites/1/livestreams

**Comment by Scotttie** [comment]
it saved however it seems but a 500 inbetween

**Comment by danlewis** [comment]
fixed

**Comment by Scotttie** [comment]
actually... once saved, can it go back to the list view of feeds? 
Currently it saves and sits on same page, but there's nothing more to do there.

**Comment by danlewis** [comment]
After creating, the user is now redirected to the index page
