### ISSUE TITLE
Add podcast -  has Documents?

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#138]
1. trying to add podcast file, failed, like in documents (it wasn't an audio file, but there were no instructs for it to be or error saying it was wrong)

2. BUT, when on the Add podcast screen there's a 'documents' tab - is that correct?
![screen shot 2017-10-18 at 12 03 08 pm](https://user-images.githubusercontent.com/13688091/31696367-69e009a4-b3fc-11e7-8bd5-00f70dd324c9.png)

**Comment by danlewis** [comment]
1. it was a server setup error, which is now resolved.
2. Documents - are essential all files (other than images).
