### ISSUE TITLE
Can't turn on/off User Images for events

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#14]
A lot of churches do have good Event promo images, more appropriate than our override images. 
It be nice to have a way to either allow their images or our images.
This would be for all events of that church, not individual events.

**Comment by Scotttie** [comment]
Can't find how to turn this feature on (which is rumoured to be implemented)
Could be placed either:
- the same spot FB tickboxes are listed to show events or news or not
- on top of the list of FB feeds on site.

AND should it be default on (use user image)?

**Comment by lsamon** [comment]
This feature has been enabled and will be pushed today. 

Scott can you test this out and verify.

**Comment by Scotttie** [comment]
nicely done.
