### ISSUE TITLE
Upload not working when clicking 'documents' and then back to 'upload'

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#141]
Upload not working when clicking over to 'documents' and then back to 'upload'
You said: We need to refresh the page without [mumble mumble ] turbo links [mumble mumble] fixed!!

It seems to be some kind of refreshing issue. jumping back and forwards it will and won't work sometimes.

Intermittent, sometimes it's broken all the time.
At one stage we couldn't upload to docs at all, but can elsewhere.

i can have two browsers opened and one works the other doesn't at the same time.

it never starts working again or breaking again without leaving the screen and coming back.

**Comment by danlewis** [comment]
please try again.

**Comment by Scotttie** [comment]
no, you fix it again.... :P

**Comment by Scotttie** [comment]
Think it's fixed. Good job pro!
