### ISSUE TITLE
Google Analytics reports

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#144]
Finish this off at some stage.
auto generated analytics code or user created....

**Comment by Scotttie** [comment]
Minimum range options: 
past 7/30/90 days, and all time

-number of User visits
-number of times individual Pages Viewed
-number of visits by Country, 
-and City 

If you really want, but to as necessary:
-Acquisition overview
-Referral Channels
-Landing Page
-Mobile Overview (compares desktop, mobile and tablet)

**Comment by danlewis** [comment]
reports added

**Comment by Scotttie** [comment]
Will wait to see if the data turns up...

**Comment by danlewis** [comment]
data no turns up :)
