### ISSUE TITLE
Add social made foolproof

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#145]
Is there a clever way we can accept different combos of a FB name?

eg
https://www.facebook.com/AdventistBookCentreSydney (isn't accepted)
https://www.facebook.com/AdventistBookCentreSydney/?ref=br_rs (neither)
Adventist Book Centre Sydney (isn't either)
AdventistBookCentreSydney (only)

OR maybe, at minimum, a hint that shows exactly what is accepted:
eg  www.facebook.com/**AdventistBookCentreSydney**/

**Comment by danlewis** [comment]
added
