### ISSUE TITLE
Document list edit jumps you into the list

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#146]
https://dashboard.adventist.place/dashboard/sites/1/document_lists/1

if I click edit on an existing Doc list, and click save or cancel, I am not returned to the list of lists, but am taken into that list without asking.

I'm guessing this is a result of the good feature of when creating a new list and then automatically ending up in the list to start adding items after saving the new list. Don't take that away. 

A low issue this one.

**Comment by danlewis** [comment]
The edit document list page can be accessed from two places - the Document list index page( the one that shows all the lists) or the document list show page(the one that shows all the documents in the list)

When cancelling or saving I need to choose to redirect back to one of those pages. I chose the document list show page as the most likely of the two to be wanted by the user.
