### ISSUE TITLE
Override Site Name

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#15]
Not all churches are called:  [name] Seventh-day Adventist Church.
eg Burwood Adventist Community Church, 
But when on SC it has to display a 'short name' with the ending 'Seventh-day Adventist Church' under it.
Ability to override the lower SDA text would be better.

![screen shot 2017-02-21 at 3 43 00 pm](https://cloud.githubusercontent.com/assets/13688091/23151088/750db41e-f84c-11e6-8cc3-1a4a7e06edd4.png)

**Comment by danlewis** [comment]
This has been implemented
