### ISSUE TITLE
Search bar results unexpected

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#165]
I search for 'demodale' the site name, but nothing comes up
I search for 'adventist' or 'media' and demodale comes up.
the site was called Adventist Media but I changed it in general settings

I suspect it's search and results are different 'fields' of the same listing. Using the ACloud name, not the user defined name

ACTUALLY: Adventist media still shows on the LHS menu, but with a D icon. That may need to sync too to say Demodale? 

Same with the browser tab title, it's adventist media not demodale.

**Comment by danlewis** [comment]
should be resolved now. Was showing the short name rather than custom name
