### ISSUE TITLE
attempting to add a domain 500's after clicking save

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#171]
/ \
        / _ \
       | / \ |
       ||   || _______
       ||   || |\     \
       ||   || ||\     \
       ||   || || \    |
       ||   || ||  \__/
       ||   || ||   ||
        \\_/ \_/ \_//
       /   _     _   \
      /               \
      |    O     O    |
      |   \  ___  /   |
     /     \ \_/ /     \
    /  -----  |  --\    \
    |     \__/|\__/ \   |
    \       |_|_|       /
     \_____       _____/
           \     /
           |     |

**Comment by danlewis** [comment]
fixed it
