### ISSUE TITLE
can't search for custom place name when 'adding site' 

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#177]
![screen shot 2018-02-06 at 2 53 22 pm](https://user-images.githubusercontent.com/13688091/35840966-820d82c4-0b4d-11e8-9da8-779e75355f01.png)
Perhapse need to be able to search for the 'new/edited' name of a Place? Not just the Cloud name?

**Comment by danlewis** [comment]
entity name searches in Adventist Cloud which has no knowledge of a sites customised name or if that site even exists. I think the cloud name should be fine, but if becomes an issue we can reopen
