### ISSUE TITLE
Search needs better results

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#18]
This is tricky to solve, but also a key feature that isn't working for the community.

eg 1. searching for 'Dalcross' (which is a hospital name) does not appear but is in the system 
It does not appear in the dropdown or if you hit enter
Search for:
Adventist Hospital
Dalcross 
Dalcross Adventist 
Dalcross Adventist Hospital
(da) is the only search that works

eg 2. search for 'avondale' and hit enter and you end up in NZ (making people select from the dropdown and not allowing ENTER might help.)

**Comment by danlewis** [comment]
Adventist Place no longer deals with search.
