### ISSUE TITLE
Wrong url for notification's 'view' for submissions

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#182]
I can view a submission at 
https://dashboard.adventist.place/dashboard/sites/1/form_submissions/1

but when I click the 'view' link from the notification bell dropdown, it removes the 's' in sites and does not connect:

https://dashboard.adventist.place/dashboard/site/1/form_submissions

**Comment by danlewis** [comment]
fixed for all new notifications -nice pick up! (old notifications will still have the old url)
