### ISSUE TITLE
Podcast feed 500

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#183]
this link 
https://dashboard.adventist.place/podcasts/4/feed
(500 error)

is on the podcast page
https://dashboard.adventist.place/dashboard/sites/1/podcasts/4

Also, Please comment, is this feed link what you could add to Tunes to end up in their directory?
if no, can we have an 'rss' feed generated people can submit, please?

**Comment by danlewis** [comment]
fixed
