### ISSUE TITLE
www.adventist.place httpS error

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#184]
Is this the promo 'home' of AdPlace?
Does the old Simple Church WP site (https://simple.adventistchurch.com/) need to be the landing page of https://www.adventist.place/ (and updated?)

**Comment by danlewis** [comment]
fixed

**Comment by Scotttie** [comment]
500 fixed but httpS error: [www.adventist.place](url)

**Comment by danlewis** [comment]
i believe that is just a DNS caching issue on your browser. try on a browser you haven't been to the URL on
