### ISSUE TITLE
Facebook Link Acceptance Changes/bug

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#19]
![screen shot 2017-02-22 at 3 12 00 pm](https://cloud.githubusercontent.com/assets/13688091/23445616/be612502-fe90-11e6-8974-659ad4f80a32.png)
When confirming a Facebook link request as a user: 
1. the email does not mention news feed items (only events and photos)
2. the conformation screen (attached) also does not mention news feed items (only events and photos)
3. the 'Visit Test' link pictured (Test was the site name) take me to https://adventistchurch.com/ (no sub domain)

**Comment by danlewis** [comment]
possibly all fixed for next release
