### ISSUE TITLE
Sign up trick

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#199]
This page is cool! https://dashboard.adventist.place/signup

BIT it confused me and could others.

it looks like the right box, with it's first sentence, is asking you to fill in the form if you have an account. (the link looks identical to the text so don't  know sign in is a link)

Can we move 3 lines in a clockwise fashion and I think that is unmistakable then:

- 'A myAdventist account gets you into many Adventist sites.' go up to where:
-  'Create your myAdventist account' is, and that go to where:
- 'Already have a myAdventist account? Sign in' is, which goes to where:
- 'A myAdventist account gets you into many Adventist sites.' was.

**Comment by danlewis** [comment]
resolved
