### ISSUE TITLE
Conference page tweaks

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#29]
1. I need 'global' Search capability on the root https://places.adventistchurch.com/conferences
I get email requests like  "can you change the pogogo church time to 9:30." 
Do you know what conference pogogo church is in to go edit it? Currently i need to click on the correct conference to be able to start to search.
So a global search will save me randomly trying the 30 conferences to find pogogo.

2. what about union and division entires? EG AUC, or my Demo Church (SPD) - they are not in any listed conferences. I need admin view to see higher level listings.

3. Can we still have a 'who's using simple church' "www" tag on the list, or even better, a filter to view only Simple Sites?

**Comment by danlewis** [comment]
Scott - please review

**Comment by Scotttie** [comment]
Thanks for the tweeeeks!
