### ISSUE TITLE
Turn on non-church websites

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#31]
Now we have non-church site content capabilities, we need to be able to turn it on - SC is currently locked down to churches only still. ("must be a church" validation strikes when trying to turn on a site for a non church place)

![screen shot 2017-03-28 at 8 40 54 am](https://cloud.githubusercontent.com/assets/13688091/24379331/64846f3c-1392-11e7-9ae5-9ac58a67ec9f.png)

![screen shot 2017-03-28 at 8 37 00 am](https://cloud.githubusercontent.com/assets/13688091/24379267/127558fa-1392-11e7-9ce7-02b491155a06.png)

**Comment by Scotttie** [comment]
NOTING: I need this to progress with the netAdventist transition

**Comment by lsamon** [comment]
This issue has been resolved. Awaiting for the changes to be pushed to production.

**Comment by danlewis** [comment]
Fixed and live please test
