### ISSUE TITLE
Deleting card doesn't 'appear' to delete - (currently needs refresh)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#32]
If I delete a card, I can still reorder it, and need to refresh the page before it disappears. This will freak people out and they will try to re-delete.
(gives 500 if your try delete/edit again)

**Comment by Scotttie** [comment]
lsamon discovered the card does delete instantly if you refresh after creating a new card. This issue is when creating the new card it gives it a different ID name initially.
lsamon also discovered the mouseover and click was deceptive on the add new card button, you had to click on the text, despite visually you assume it was highlighted ready to click.
Will closes once seen fixed and working.

**Comment by danlewis** [comment]
fixed card deleting and added a default position. When adding a new card it also opens up a lightbox rather than simply adding it.
