### ISSUE TITLE
URGENT: Can't turn on new sites (or off)

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#33]
Some urgent work needs doing to enable choosing themes again, particularly as we can't turn on a new site currently as it requires a theme to be set - and we can't seem to do that.

**Comment by Scotttie** [comment]
Can't turn off a site either.
https://places.adventistchurch.com/dashboard/places/331/website needs turning off

**Comment by danlewis** [comment]
removed theme validation. Please test
