### ISSUE TITLE
Can't delete final (primary) url if no longer having website

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#34]
If you have the website option NOT ticked, you should be able to delete ALL URLs for the place.

**Comment by danlewis** [comment]
fixed

**Comment by Scotttie** [comment]
Now you can delete all domains (yay) but can also now have 'website available' still ticked (and unticked and ticked again) without having any domain - there should probably be some requirement for a domain to be present when 'website available' is ticked to avoid user confusion? 
As in recommendation ticket, if these two items were on same screen it would be easier to manage.
"Website available? oh, you ticked it, cool, so enter a domain below - can't save as 'available' unless you have something entered!" [i think that's the Ruby code written for you right there]
