### ISSUE TITLE
Image selector is global images, not local.

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#37]
The image selector (eg banner select) is showing ALL images on SC.
This list will grow uncontrollably and will be very tedious to find you pic of your church again, now that christmas is over and you want to revert to your original image.

Can we only show 'site' uploaded images, or perhaps include system images also - but the key is to hide other site images above all else.

![screen shot 2017-03-28 at 10 58 54 am](https://cloud.githubusercontent.com/assets/13688091/24382976/9a406c94-13a5-11e7-88ae-4ecdace6bae0.png)

**Comment by danlewis** [comment]
The dashboard place chooser shows all images that were either:
a) uploaded by you
b) uploaded by your team
c) uploaded to the place

As you're part of the admin team you pretty much get to see every image.

For a person who only has access to that place however, they would only see a) and c) which be very few images for most people.
