### ISSUE TITLE
Mailchimp - Ugly broken list

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#44]
I get this ugliness in the Dashboard (and clicking on it gets a 404 - but the form works on front end):

![mc name](https://cloud.githubusercontent.com/assets/13688091/24430098/ba3389da-1460-11e7-8290-78e82a0387df.png)

https://places.adventistchurch.com/dashboard/places/926/mailing_lists

**Comment by Scotttie** [comment]
Also noting - can't delete/edit this entry

**Comment by danlewis** [comment]
fixed and live.

louis has now added a 60 character limit for the name

deleting/edit was visible - you just need to scroll horizontally as the text took up way to much room
