### ISSUE TITLE
Pastors linked up

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#52]
Having current pastor/principals names and emails associated with a Place to enable notifications/verifications would be good. 
But must be auto updated/managed from elsewhere.

**Comment by danlewis** [comment]
Can you clarify more about what you mean by "associated with a Place to enable "
Also what type of notifications/verifications?

**Comment by Scotttie** [comment]
I guess it's 'pastors management' I'm thinking of.
If our system is going to be THE place conferences manage what church Pastors are 'reps' for what churches, then close the ticket, all good. (Now, seeing what Lisa is doing, it seems like our system will the core online source of Pr placements?)
BUT if conferences are managing Pastors elsewhere online in some other 'app', can we pull in those details automatically.

**Comment by Scotttie** [comment]
OH... and the other part I meant, it would be handy to be able to contact this PR easily for when someone tries to 'claim/edit' a place so we can quickly go "Hi Pr, do you know 'user' as they are trying to edit your church site. Should we let them in? OR do you approve these suggested changes?" 
that kind of thing.
