### ISSUE TITLE
500 when Adding cards: Youth, Mailing list

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#56]
When I add the cards Youth and Mailing list I get a 500 error - though I didn't count all 500 - I took the error's word that the error was 500 in total. 
(I was adding to a school Place, not a church Place, whether that matters...)

**Comment by danlewis** [comment]
fixed and live

**Comment by Scotttie** [comment]
Youth works, but adding 'Mailing list' to below still 500's
https://places.adventistchurch.com/dashboard/places/805/site_cards

**Comment by danlewis** [comment]
Fixed again :)
