### ISSUE TITLE
Faith FM podcast?

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#6]
Is there a feed we can add Faith FM to the podcasts?
https://faithfm.com.au

**Comment by alexgreendesign** [comment]
There is this:

http://tunein.com/radio/Faith-FM-Australia-s163884/

**Comment by Scotttie** [comment]
Dan, you might need to look for a feed we can accept there, (Can we do actually streaming, or only XML lists? Maybe this is turing into a feature request?)
each url I've tried has failed.

**Comment by alexgreendesign** [comment]
I can check with Michael for a direct feed. How exactly do you need it?
