### ISSUE TITLE
'VideoTabs not disapearing 

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#60]
![screen shot 2017-04-04 at 3 37 56 pm](https://cloud.githubusercontent.com/assets/13688091/24643607/65310e3e-1952-11e7-9fd7-83787f230b25.png)

Even though I don't have a video or podcast card, the links still appear up the top right side. They should probably disappear.

**Comment by danlewis** [comment]
is this still an issue?

**Comment by Scotttie** [comment]
yes. when I remove the podcast and video cards, the header tabs remain.

**Comment by danlewis** [comment]
The cards are not related to the headers. E.g. you can have videos on your site but choose not to have them on the home page.
Videos should only hide from the nav when the site is not subscribed to any videos. The same applies for podcasts
