### ISSUE TITLE
Mobile View Columns

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#66]
Poscasts, Watch and News need reviewing of how they display/align on mobile devices.

![image1](https://cloud.githubusercontent.com/assets/13688091/24986899/3757166c-2040-11e7-95de-d8dccd8a6b17.PNG)
![image2](https://cloud.githubusercontent.com/assets/13688091/24986900/375cc01c-2040-11e7-9442-663e033c7706.PNG)
![image3](https://cloud.githubusercontent.com/assets/13688091/24986901/375f6fba-2040-11e7-8112-5a9490717327.PNG)

this will explain better: http://media.giphy.com/media/YMbTtqePy7meY/giphy-tumblr.gif

**Comment by lsamon** [comment]
This has been completed. pending changes to be pushed to production
