### ISSUE TITLE
Dashboard Page Titles

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#67]
Is it possible to have the actual dashboard 'page titles' appear as page titles - not just the word 'Dashboard' for each page. This would make viewing tabs, history, bookmarks more useful.

perhaps:  [Church short name] [Page title] - Simple Church Admin

eg
Waitara Location - Simple Church Admin

**Comment by danlewis** [comment]
page title now shows in the dasboard

**Comment by Scotttie** [comment]
Better, indeed, but any chance of adding 'dashboard' after the page name, or even better the title of the dashboard page at the end?
right now if you have the dashboard page opened, and the live site opened, they are identical icon and title - though very different pages.

**Comment by danlewis** [comment]
As advised the title now reads "Dashboard - {page title}"
