### ISSUE TITLE
FB News Tweaks 

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#69]
FB news is looking great! two polishings...
1. FB feed name and publish date: can they be RHS of icon?
2. can we have some sort of separation of the user content and the shared post, like a <HR> or something? Currently all text content is there (good!) but user and shared content runs straight on together with no differentiation.

**Comment by lsamon** [comment]
This has been completed and pushed to master. Scott can you confirm and close this issue if it is done?
