### ISSUE TITLE
SC listing show web Address

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#74]
Google is picking up search.adventistchurch.com listings pages (not the results listing, one click further in if they don't have a site). 
Can that search listing page display the url of their website too, if one is entered and they arrive their form Google??
![screen shot 2017-05-09 at 3 57 42 pm](https://cloud.githubusercontent.com/assets/13688091/25837255/3e598a54-34d0-11e7-8141-c6f91321292d.png)

AND, while we're having fun, what about the search listing results showing any social media icons?
Maybe even a link to website instead of the title going there? the title could go to the listing? dunno.

![screen shot 2017-05-09 at 4 00 54 pm](https://cloud.githubusercontent.com/assets/13688091/25837340/b1989ffa-34d0-11e7-99e8-7ee0d8d454a6.png)

**Comment by danlewis** [comment]
If a place has a website, it should probably not be allowed to have a search listing page. Would this also resolve the issue?

**Comment by Scotttie** [comment]
Yeah! I think my logic goofed on this one! Good point. Closing

**Comment by Scotttie** [comment]
Or, maybe it's my memory of the key issue and reporting that is failing, not my logic...
The summary listing is still available if simple church page is turned on, and i suspect is also available if a website is present. SO if google has the place holder in it's results people can end up on the listing page. anyway, leave it for now...
