### ISSUE TITLE
Samoa is showing 'region' code in address but hasn't field to enter it

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#75]
see address of http://siufagaschool.adventistchurch.com/
dash: https://places.adventistchurch.com/dashboard/places/941/address

**Comment by danlewis** [comment]
Fixed - hooray

**Comment by Scotttie** [comment]
Is it really fixed? I may not be on latest version
See address at bottom of: http://siufagaschool.adventist.org.ws/
There's {code} on the screen for me.
![screen shot 2017-08-14 at 12 04 40 pm](https://user-images.githubusercontent.com/13688091/29255879-c67934e8-80e8-11e7-8373-e23eb1e82566.png)

**Comment by danlewis** [comment]
This was a caching issue - it's now resolved. Interesting clicking the clear cache feature in the dashboard didn't actually clear the cache..
