### ISSUE TITLE
bread crumbs tweak

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#76]
![screen shot 2017-05-17 at 9 28 52 am](https://cloud.githubusercontent.com/assets/13688091/26132393/556d4f6e-3ae3-11e7-8bc7-cc62f261ff16.png)

1. instead of 'places' this shoudl probably read the name of the conference clicked.

2. the '/all' at the end of practically each crumb trail seems redundant, and too 'deep' even. The final item on the list should be the current location, (eg '[conference name]' on https://places.adventistchurch.com/conferences/18/places should be last AND it should not be a link.)  Currently, the page your viewing, while is second from top, is a link to current page (which is not needed)

3. maybe the trail should be:  dashboard / conference / South New Zealand

4. and https://places.adventistchurch.com/admin/locations has the wrong 'crumb'. Haven't checked them all.

**Comment by danlewis** [comment]
1-3: Made some corrections.. changing whole app may take a fair while
4. fixed.
