### ISSUE TITLE
Info Card description field size and size

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#77]
1. The description fields (particularly on the Info card, but the About card too) needs to be several times taller. It's a pain to resize each time I'm editing/formatting content.

2. a character countdown/up would be very useful in this field. its pure guess work.

3. a limit on characters in the title and subtitle would be good. not too small but not unlimited. 100?

4. ability to swap image to left side? we'll see what users request when we let them in.

**Comment by danlewis** [comment]
1. fixed
2. Counter implemented.
3. title and subtitle are standard text fields like any other in Simple Church which are 255 characters max.
4. not a priority at this point

**Comment by Scotttie** [comment]
1, 2 and 4 ok.
respectfully disagree on 3. there is no limit to the title and subtitle fields

![screen shot 2017-08-15 at 2 52 11 pm](https://user-images.githubusercontent.com/13688091/29302666-5c5f7e5a-81c9-11e7-93da-da79165aa692.png)
![screen shot 2017-08-15 at 2 51 59 pm](https://user-images.githubusercontent.com/13688091/29302667-5c6036ce-81c9-11e7-9f5b-b0adba9b2354.png)

**Comment by danlewis** [comment]
lol good point. the maximum is now 100 characters for title and subtitle
