### ISSUE TITLE
Easy bulk view and update of church details/Pastors

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#78]
From LisaK in NZ:

> "Do you know if there is a way for a Conference to download the list of churches under them? - https://places.adventistchurch.com/conferences
> I want some of our staff to check the churches, contact details and pastors listed."

The key element for a place which will change more regularly than anything else is: Pr, phone, email.

Probably just an Excel download of church name, PR, Phone, Email - then the list can be looked over and changed highlighted to be enter by an admin

Another option is an on-screen list view of all places in a conference and the core details (PR, Phone, Email) with a 'quick edit' ability to update certain fields without the need to click around screens.

**Comment by danlewis** [comment]
The pastors feature will be moving to Adventist Church hopefully soon and hence we would not add this to Simple Church
