### ISSUE TITLE
500 if click 'add language' without selecting one

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#79]
Is not 100% intuitive. The invitation to 'add language' before one is selected is too much for some.

It gives a 500 error (to us only) if clicked 'Add language' without selecting the button. 

Would be better if button was greyed out until a language is selected, THEN you can click it.
![screen shot 2017-05-17 at 12 59 37 pm](https://cloud.githubusercontent.com/assets/13688091/26136747/12dd0914-3b01-11e7-9648-5cff08c3e262.png)

**Comment by danlewis** [comment]
I don't get a 500 error but instead an alert pop up with a message. I improved the error message but i'm not sure its necessary to disable the button.. Try the new non-500 error version
