### ISSUE TITLE
Moving reps between conferences

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#81]
Reps will be moving between conferences regularly (Pr's move interstate) how can this be handled?

Does a conference delete the outgoing, and the other confernece re-make the rep? (how it is now)

Or does the rep get removed from all (or most) roles in conference, and ends up in a pool to be picked up by another conference.

Does the new conference have to wait for the rep to be released before being pulled into their conference?

If only all pastors all had a unique ID (Their official ad.org email?)

AND: Can one delete a rep if it's a duplicate?

**Comment by Scotttie** [comment]
Form Lisa:
Getting back to you about the Reps.

Ok I can see if we transfer Reps between Conferences this could become an issue as you would have to wait for the other end to approve or move the staff. 
Some of our staff are not actually pastors. They start as an assistant and then end up moving into the roll. Some have left after some time and have returned to a normal job. So we would need the ability to delete or make them for deletion. Lol sounds so tragic!
I guess this just depend on how many conferences start using it and keeping their info up to date on their pastors and churches. I know ours are a mess I have been trying to sort them out and get it right.

**Comment by danlewis** [comment]
This information will be managed in Adventist Cloud instead
