### ISSUE TITLE
Setting a Location - issues

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#90]
1. In locations: It auto fills the country but when you enter a 'suburb' it often ignores the country and goes off to USA and says 'here you are'. Frantic scrolling is then needed to get your marker back to the tiny pacific island you're looking for. It should default to the county, and if it finds the suburb, then move there within that country., if not don't go international!

2. Maybe instead of an auto lookup - which breaks things if you have it set and need to alter text, only update map when you click 'update map'....

3. the 'auto suggest an address' does not seem to populate the fields when selecting one.

4. are we prepared for the water levels rising, I fear the oceans will overflow the map square boundaries and go all over the screen. perhaps a bold border should be put around the map to contain the tides, or a pixel pump installed????

**Comment by danlewis** [comment]
1. i was unable to replicate this
2. as an experiment - i've turned off the map auto lookup when editing an address.
3. this was a bug thats been fixed
4. advise users not to use map during super moons

**Comment by danlewis** [comment]
Hooray - a solution was found. Fixed
