### ISSUE TITLE
Quick Add times broken

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#92]
Two issues:

1. 'Quick add' added times are showing 5 'saturday's' in the 'time data' code output (as Alex - he spotted it) despite being set to mon-fri
https://places.adventistchurch.com/dashboard/places/864/place_times

2. these quick add times are not showing on the search page results either.
https://search.adventistchurch.com/listings/map?utf8=%E2%9C%93&q=Hospitals+%26+Clinics&place_type=&button=

**Comment by danlewis** [comment]
Fixed bug where quick add times where 1 day off. This will be in the next release

**Comment by Scotttie** [comment]
Are you happy with the fix to the above point 1, Alex?

**Comment by alexgreendesign** [comment]
Just noticed this - yep, all good.
