### ISSUE TITLE
URGENT! ALL times seem to be 1 hr early and am/pm inversed

### ISSUE THREAD

**Issue by Scotttie** [adventistmedia/simple_church#98]
It appears church times are 'all' (noted in three consecutive random checks) 1 hour too early and Pm instead of AM.

eg The vine needs to be 10:30am but shows 9:30pm
https://places.adventistchurch.com/dashboard/places/177/place_times
https://places.adventistchurch.com/admin/place_submissions/153

NOTE TO SCOTT: I edited this one manually to correct time, and may need to change it back when a global fix is done.
Wangaratta needs to be:
Sabbath School Bible Study: 9:55am
Worship Service: 11:15am

**Comment by danlewis** [comment]
Fixed. And I've updated all the place times that were changed since the update including Vine and Wangaratta.
